#FROM oven/bun:1 AS base
FROM docker.1ms.run/oven/bun:1 AS base
WORKDIR /app

FROM base AS install
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

FROM base AS release
COPY --from=install /app/node_modules ./node_modules
COPY . .

#ENV PORT=3000
#EXPOSE 3000

CMD ["bun", "run", "cli.ts"]
# CMD ["bun", "run", "server.ts"]
